name: Varbase API - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - jsonapi
  - openapi
  - openapi_jsonapi
  - openapi_rest
  - openapi_ui_redoc
  - openapi_ui_swagger
  - simple_oauth
  - restui
  - jsonapi_extras
  - jsonapi_defaults
config:
  import:
    jsonapi: '*'
    openapi: '*'
    openapi_jsonapi: '*'
    openapi_rest: '*'
    openapi_ui_redoc: '*'
    openapi_ui_swagger: '*'
    simple_oauth: '*'
    restui: '*'
    jsonapi_extras: '*'
    jsonapi_defaults: '*'
  actions:
    jsonapi_extras.settings:
      simpleConfigUpdate:
        path_prefix: api
        include_count: false
        default_disabled: true
        validate_configuration_integrity: true
    user.role.site_admin:
      grantPermissions:
        - 'access openapi api docs'
        - 'access view api docs entity operation'
        - 'access view json entity operation'
